import { Header } from '@/components/HeaderWrapper'
import { Inter } from "next/font/google"
import Head from 'next/head'
import "./globals.css"

const inter = Inter({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const authorized = false;
  return (
    <>
      <Head>
      <meta name="frog" content="05ef141a1925c5890688f13668f2e303" />
      </Head>
      <html lang="en">
        <body className={inter.className}>
          {authorized ? <Header /> : null}
          {children}
        </body>
      </html>
    </>
  );
}
